CREATE TABLE grupo
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255),
    CONSTRAINT pk_grupo PRIMARY KEY (id)
);

CREATE TABLE grupo_permissoes
(
    grupo_id      BIGINT NOT NULL,
    permissoes_id BIGINT NOT NULL,
    CONSTRAINT pk_grupo_permissoes PRIMARY KEY (grupo_id, permissoes_id)
);

ALTER TABLE grupo_permissoes
    ADD CONSTRAINT fk_gruper_on_grupo FOREIGN KEY (grupo_id) REFERENCES grupo (id);

ALTER TABLE grupo_permissoes
    ADD CONSTRAINT fk_gruper_on_permissao FOREIGN KEY (permissoes_id) REFERENCES permissao (id);