CREATE TABLE usuario
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome          VARCHAR(255),
    email         VARCHAR(255),
    senha         VARCHAR(255),
    data_cadastro TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE usuario_grupos
(
    grupos_id  BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT pk_usuario_grupos PRIMARY KEY (grupos_id, usuario_id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE usuario_grupos
    ADD CONSTRAINT fk_usugru_on_grupo FOREIGN KEY (grupos_id) REFERENCES grupo (id);

ALTER TABLE usuario_grupos
    ADD CONSTRAINT fk_usugru_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id);