CREATE TABLE produto
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    preco     DECIMAL,
    ativo     BOOLEAN,
    CONSTRAINT pk_produto PRIMARY KEY (id)
);