CREATE TABLE pedido
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subtotal             DECIMAL,
    taxa_frete           DECIMAL,
    valor_total          DECIMAL,
    status               VARCHAR(255),
    data_criacao         TIMESTAMP,
    data_confirmacao     TIMESTAMP,
    data_a_caminho         TIMESTAMP,
    data_cancelamento    TIMESTAMP,
    data_entrega         TIMESTAMP,
    forma_pagamento_id   BIGINT                                  NOT NULL,
    restaurante_id       BIGINT                                  NOT NULL,
    cliente_id           BIGINT                                  NOT NULL,
    endereco_cep         VARCHAR(255),
    endereco_logradouro  VARCHAR(255),
    endereco_numero      VARCHAR(255),
    endereco_complemento VARCHAR(255),
    endereco_bairro      VARCHAR(255),
    cidade_id            BIGINT,
    CONSTRAINT pk_pedido PRIMARY KEY (id)
);

ALTER TABLE pedido
    ADD CONSTRAINT FK_PEDIDO_ON_CIDADE FOREIGN KEY (cidade_id) REFERENCES cidade (id);

ALTER TABLE pedido
    ADD CONSTRAINT FK_PEDIDO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES usuario (id);

ALTER TABLE pedido
    ADD CONSTRAINT FK_PEDIDO_ON_FORMAPAGAMENTO FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento (id);

ALTER TABLE pedido
    ADD CONSTRAINT FK_PEDIDO_ON_RESTAURANTE FOREIGN KEY (restaurante_id) REFERENCES restaurante (id);